import { useRef, useCallback } from 'react'

// ═══════════════════════════════════════════════════════════════════════════
// Pre-recorded announcement sounds (generated by server/generate_sounds.py)
// ═══════════════════════════════════════════════════════════════════════════

const SOUND_PATH = '/sound/announcement/'

// ═══════════════════════════════════════════════════════════════════════════
// Hook — server‑driven announcements
// ═══════════════════════════════════════════════════════════════════════════

export function useSoundEffects() {
  const ctxRef = useRef<AudioContext | null>(null)
  const bufferCacheRef = useRef<Map<string, AudioBuffer>>(new Map())
  const pendingRef = useRef<Set<string>>(new Set())

  /**
   * Ensure AudioContext exists and is in 'running' state.
   * Returns null if still suspended — caller should skip playback.
   */
  const getRunningCtx = useCallback((): AudioContext | null => {
    let ctx = ctxRef.current
    if (!ctx || ctx.state === 'closed') {
      try { ctx = new AudioContext(); ctxRef.current = ctx } catch { return null }
    }
    if (ctx.state === 'suspended') {
      ctx.resume().catch(() => {
        try { ctxRef.current = new AudioContext() } catch { /* ignore */ }
      })
      return null
    }
    return ctx
  }, [])

  // ── Synthesized card sound ────────────────────────────────────────

  /** Short "pia" effect when cards hit the table. */
  const playCardSound = useCallback(() => {
    const ctx = getRunningCtx()
    if (!ctx) return
    try {
      const now = ctx.currentTime
      const buf = ctx.createBuffer(1, ctx.sampleRate * 0.08, ctx.sampleRate)
      const d = buf.getChannelData(0)
      for (let i = 0; i < d.length; i++)
        d[i] = (Math.random() * 2 - 1) * Math.exp(-i / (ctx.sampleRate * 0.015))
      const src = ctx.createBufferSource()
      src.buffer = buf
      const flt = ctx.createBiquadFilter()
      flt.type = 'highpass'
      flt.frequency.setValueAtTime(3000, ctx.currentTime)
      flt.frequency.exponentialRampToValueAtTime(800, ctx.currentTime + 0.06)
      const gn = ctx.createGain()
      gn.gain.setValueAtTime(0.25, ctx.currentTime)
      gn.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.08)
      src.connect(flt); flt.connect(gn); gn.connect(ctx.destination)
      src.start(now); src.stop(now + 0.08)
    } catch { /* audio n/a */ }
  }, [getRunningCtx])

  // ── Server‑driven announcement playback ────────────────────────────

  /** Wake AudioContext. Call on every user gesture. */
  const warmup = useCallback(() => { getRunningCtx() }, [getRunningCtx])

  /** Play a decoded AudioBuffer immediately. */
  const playBuffer = useCallback((buf: AudioBuffer) => {
    const ctx = getRunningCtx()
    if (!ctx) return
    try {
      const src = ctx.createBufferSource()
      src.buffer = buf
      const gn = ctx.createGain()
      gn.gain.value = 1.0
      src.connect(gn); gn.connect(ctx.destination)
      src.start(0)
    } catch { /* playback failed */ }
  }, [getRunningCtx])

  /**
   * Play a server‑specified announcement sound.
   * @param soundPath e.g. "dad/single_KING", "mom/pass"
   */
  const playAnnouncement = useCallback((soundPath: string) => {
    const url = `${SOUND_PATH}${soundPath}.mp3`

    // Cache hit → instant
    const cached = bufferCacheRef.current.get(url)
    if (cached) { playBuffer(cached); return }

    // Deduplicate in‑flight fetches
    if (pendingRef.current.has(url)) return
    pendingRef.current.add(url)

    fetch(url)
      .then(r => { if (!r.ok) throw Error(); return r.arrayBuffer() })
      .then(buf => {
        const ctx = ctxRef.current
        if (!ctx) return
        ctx.decodeAudioData(buf, ab => {
          bufferCacheRef.current.set(url, ab)
          pendingRef.current.delete(url)
          playBuffer(ab)
        }, () => { pendingRef.current.delete(url) })
      })
      .catch(() => { pendingRef.current.delete(url) })
  }, [playBuffer])

  return { playCardSound, playAnnouncement, warmup }
}
